context:
  name: warcio
  version: "1.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/warcio-${{ version }}.tar.gz
  sha256: f1f19ac2678b30309c62d310f286b5c3216bbc0542229b96fe89e1906dca4a6b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - warcio = warcio.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - six

tests:
  - python:
      imports:
        - warcio
      pip_check: true
      python_version: ${{ python_min }}
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - warcio --help

about:
  summary: Streaming WARC (and ARC) IO library
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  homepage: https://github.com/webrecorder/warcio

extra:
  recipe-maintainers:
    - hadim
